site_name: CloudHSM Workshop
extra_javascript:
  - 'javascripts/input_copy.js'
theme:
  name: 'mkdocs'
nav:
    - Inicio: index.md
    - Inicialización: cluster_init.md
    - Gestión de llaves: key_management.md
    - Website: website.md
    - ACM: acm.md
    - KMS: kms.md
